# Virtual Labs QA Tool Configuration

[general]
version = "1.0.0"
default_model = "gemini-2.0-flash"
available_models = [
    "gemini-2.0-flash",
    "gemini-2.0-flash-lite", 
    "gemini-2.5-flash-preview-05-20"
]
temp_cleanup = true

[llm]
temperature = 0.2
max_tokens = 100000

[weights]
# Component weights for final score calculation (must sum to 1.0)
structure = 0.25
content = 0.50
simulation = 0.25

[thresholds]
# Minimum scores and penalties
structure_minimum = 3.0
template_penalty = 0.3
good_score = 8.0
satisfactory_score = 5.0
minimum_content_length = 50

[content_evaluation]
template_repo_url = "https://github.com/virtual-labs/ph3-exp-template"
template_similarity_threshold = 0.7
enable_template_comparison = true
